<?php
/**
 * Body7Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Body7Test Class Doc Comment
 *
 * @category    Class
 * @description Body7
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Body7Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body7"
     */
    public function testBody7()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "primary_address"
     */
    public function testPropertyPrimaryAddress()
    {
    }

    /**
     * Test attribute "primary_phone"
     */
    public function testPropertyPrimaryPhone()
    {
    }

    /**
     * Test attribute "race"
     */
    public function testPropertyRace()
    {
    }

    /**
     * Test attribute "emergency_contact"
     */
    public function testPropertyEmergencyContact()
    {
    }

    /**
     * Test attribute "emergency_phone"
     */
    public function testPropertyEmergencyPhone()
    {
    }
}
