<?php
/**
 * InlineResponse20010Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20010Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20010
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20010Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20010"
     */
    public function testInlineResponse20010()
    {
    }

    /**
     * Test attribute "recurring_fees"
     */
    public function testPropertyRecurringFees()
    {
    }

    /**
     * Test attribute "one_time_fees"
     */
    public function testPropertyOneTimeFees()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "membership_type"
     */
    public function testPropertyMembershipType()
    {
    }

    /**
     * Test attribute "applied_discount_group_ids"
     */
    public function testPropertyAppliedDiscountGroupIds()
    {
    }

    /**
     * Test attribute "home_branch"
     */
    public function testPropertyHomeBranch()
    {
    }

    /**
     * Test attribute "billing_cycle"
     */
    public function testPropertyBillingCycle()
    {
    }

    /**
     * Test attribute "billing_cyles"
     */
    public function testPropertyBillingCyles()
    {
    }

    /**
     * Test attribute "draft_day"
     */
    public function testPropertyDraftDay()
    {
    }

    /**
     * Test attribute "draft_days"
     */
    public function testPropertyDraftDays()
    {
    }

    /**
     * Test attribute "auto_renew"
     */
    public function testPropertyAutoRenew()
    {
    }

    /**
     * Test attribute "next_process_date"
     */
    public function testPropertyNextProcessDate()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "renew"
     */
    public function testPropertyRenew()
    {
    }

    /**
     * Test attribute "members"
     */
    public function testPropertyMembers()
    {
    }

    /**
     * Test attribute "age_group_rules"
     */
    public function testPropertyAgeGroupRules()
    {
    }

    /**
     * Test attribute "allow_payment"
     */
    public function testPropertyAllowPayment()
    {
    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }

    /**
     * Test attribute "steps"
     */
    public function testPropertySteps()
    {
    }
}
