<?php
/**
 * InlineResponse20013FacetsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20013FacetsTest Class Doc Comment
 *
 * @category    Class
 * @description Statistical information based on the current query.  This property will only exist if &#x60;include_facets&#x60; query parameter is true.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20013FacetsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20013Facets"
     */
    public function testInlineResponse20013Facets()
    {
    }

    /**
     * Test attribute "locations"
     */
    public function testPropertyLocations()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "days_of_week"
     */
    public function testPropertyDaysOfWeek()
    {
    }

    /**
     * Test attribute "programs"
     */
    public function testPropertyPrograms()
    {
    }

    /**
     * Test attribute "time_ranges"
     */
    public function testPropertyTimeRanges()
    {
    }
}
