<?php
/**
 * V3membershipcartIdcheckoutLineItemPaymentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V3membershipcartIdcheckoutLineItemPaymentsTest Class Doc Comment
 *
 * @category    Class
 * @description V3membershipcartIdcheckoutLineItemPayments
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V3membershipcartIdcheckoutLineItemPaymentsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V3membershipcartIdcheckoutLineItemPayments"
     */
    public function testV3membershipcartIdcheckoutLineItemPayments()
    {
    }

    /**
     * Test attribute "line_item_id"
     */
    public function testPropertyLineItemId()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "schedule_remaining"
     */
    public function testPropertyScheduleRemaining()
    {
    }
}
