<?php
/**
 * ProgramRegistrationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProgramRegistrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramRegistrationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptAgreements
     *
     * Accept agreements.
     *
     */
    public function testAcceptAgreements()
    {
    }

    /**
     * Test case for addRegistrationOfferingToCart
     *
     * Start program offering registration.
     *
     */
    public function testAddRegistrationOfferingToCart()
    {
    }

    /**
     * Test case for createCart
     *
     * Create a cart.
     *
     */
    public function testCreateCart()
    {
    }

    /**
     * Test case for deleteCart
     *
     * Delete a cart.
     *
     */
    public function testDeleteCart()
    {
    }

    /**
     * Test case for deleteCartPromoCodes
     *
     * Delete promo code from cart.
     *
     */
    public function testDeleteCartPromoCodes()
    {
    }

    /**
     * Test case for deleteLineItem
     *
     * Delete line item.
     *
     */
    public function testDeleteLineItem()
    {
    }

    /**
     * Test case for getAgreements
     *
     * Get agreements.
     *
     */
    public function testGetAgreements()
    {
    }

    /**
     * Test case for getCartDetails
     *
     * Get Cart Details.
     *
     */
    public function testGetCartDetails()
    {
    }

    /**
     * Test case for getCartProductBundleInstances
     *
     * Get possible instances to register for.
     *
     */
    public function testGetCartProductBundleInstances()
    {
    }

    /**
     * Test case for getCartProductBundleQuestions
     *
     * Get custom questions.
     *
     */
    public function testGetCartProductBundleQuestions()
    {
    }

    /**
     * Test case for getCartReceipt
     *
     * Get Cart Receipt.
     *
     */
    public function testGetCartReceipt()
    {
    }

    /**
     * Test case for getCartStatus
     *
     * Get Cart Status.
     *
     */
    public function testGetCartStatus()
    {
    }

    /**
     * Test case for postCartCheckout
     *
     * Checkout.
     *
     */
    public function testPostCartCheckout()
    {
    }

    /**
     * Test case for postCartPromoCodes
     *
     * Apply promo code to cart.
     *
     */
    public function testPostCartPromoCodes()
    {
    }

    /**
     * Test case for putCartPaymentAmount
     *
     * Apply payment amounts.
     *
     */
    public function testPutCartPaymentAmount()
    {
    }

    /**
     * Test case for putCartProductBundleAnswers
     *
     * Save answers.
     *
     */
    public function testPutCartProductBundleAnswers()
    {
    }

    /**
     * Test case for putCartProductBundleInstances
     *
     * Choose instances to register for.
     *
     */
    public function testPutCartProductBundleInstances()
    {
    }

    /**
     * Test case for removeProductBundle
     *
     * Remove product bundle from cart.
     *
     */
    public function testRemoveProductBundle()
    {
    }
}
