<?php
/**
 * UnitsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Daxko Operations API
 *
 * description
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@daxko.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UnitsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UnitsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUnitRelationships
     *
     * Create Relationship Source.
     *
     */
    public function testCreateUnitRelationships()
    {
    }

    /**
     * Test case for deleteUnitRelationshipSource
     *
     * Delete Relationship Source.
     *
     */
    public function testDeleteUnitRelationshipSource()
    {
    }

    /**
     * Test case for getUnitBillingMethods
     *
     * Get Unit Billing Methods.
     *
     */
    public function testGetUnitBillingMethods()
    {
    }

    /**
     * Test case for getUnitDetails
     *
     * Get Unit Details.
     *
     */
    public function testGetUnitDetails()
    {
    }

    /**
     * Test case for getUnitRelationshipTypes
     *
     * List Relationship Types.
     *
     */
    public function testGetUnitRelationshipTypes()
    {
    }

    /**
     * Test case for getUnitRelationships
     *
     * List Relationship Sources.
     *
     */
    public function testGetUnitRelationships()
    {
    }

    /**
     * Test case for updateUnitRelationshipSource
     *
     * Update Relationship Source.
     *
     */
    public function testUpdateUnitRelationshipSource()
    {
    }
}
